import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
	{
		_id: uuid(),
		name: "DUNE: The Graphic Novel, Book 1: Dune: Book 1 (Volume 1)",
		price: 5000,
		category: "books",
		rating: 3.5,
		discount: 23,
		src: "https://m.media-amazon.com/images/I/71SZk092xML._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Rick and Morty Wars Maxi Poster",
		price: 550,
		category: "wallart",
		rating: 4,
		discount: 55,
		src: "https://d1x7zurbps6occ.cloudfront.net/product/large/725123-192724.jpg",
	},
	{
		_id: uuid(),
		name: "The Mandalorian Coffee Mug",
		price: 1000,
		category: "lifestyle",
		rating: 1.6,
		discount: 35,
		src: "https://d1x7zurbps6occ.cloudfront.net/product/large/1071780-317673.jpg",
	},
	{
		_id: uuid(),
		name: "Vintage Coyboy bepop phone case - iphone 13",
		price: 2000,
		category: "accessories",
		rating: 3.6,
		discount: 15,
		src: "https://m.media-amazon.com/images/I/81ILf5dEM8L._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Tokyo Revengers Manjiro enamel pin",
		price: 2000,
		category: "accessories",
		rating: 1.6,
		discount: 35,
		src: "https://m.media-amazon.com/images/I/51AoBHBaPpL._AC_UL480_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Starwars The Mandolorian Note Book",
		price: 1500,
		category: "stationery",
		rating: 2.3,
		discount: 30,
		src: "https://d1x7zurbps6occ.cloudfront.net/product/large/1060032-316057.jpg",
	},

	{
		_id: uuid(),
		name: "Back to the future Men's Tshirt",
		price: 3500,
		category: "clothing",
		rating: 3,
		discount: 45,
		src: "https://d1x7zurbps6occ.cloudfront.net/product/large/1077870-319062.jpg",
	},

	{
		_id: uuid(),
		name: "A wrinkle in time book (paperback)",
		price: 2500,
		category: "books",
		rating: 3.2,
		discount: 9,
		src: "https://m.media-amazon.com/images/I/81yap8yKGwL._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Neon genesis evangelion  poster",
		price: 1500,
		category: "wallart",
		rating: 2.5,
		discount: 15,
		src: "https://m.media-amazon.com/images/I/61MXLfB3SiL._AC_UL480_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Ghost in the Shell Motoko Kusanagi Figurine",
		price: 850,
		category: "accessories",
		rating: 4.2,
		discount: 35,
		src: "https://m.media-amazon.com/images/I/61jPfTXDsaL._AC_UL480_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Flowers for algernon Book (paperback)",
		price: 550,
		category: "books",
		rating: 1.7,
		discount: 25,
		src: "https://m.media-amazon.com/images/I/3108OHxY7IL._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Steins gate hoodie",
		price: 4550,
		category: "clothing",
		rating: 4.7,
		discount: 60,
		src: "https://m.media-amazon.com/images/I/61vwUx+HMKL._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Starwars the Mandalorian Child bad",
		price: 2000,
		category: "lifestyle",
		rating: 4.6,
		discount: 15,
		src: "https://d1x7zurbps6occ.cloudfront.net/product/large/1106538-330116.jpg",
	},
	{
		_id: uuid(),
		name: "Serial Experiments Lain Glitch Cover NoteBook",
		price: 500,
		category: "stationery",
		rating: 3.6,
		discount: 85,
		src: "https://m.media-amazon.com/images/I/613-AD-2xnL._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Starwars Pencil case",
		price: 80,
		category: "stationery",
		rating: 4.7,
		discount: 5,
		src: "https://d1x7zurbps6occ.cloudfront.net/product/large/1060010-316060.jpg",
	},
	{
		_id: uuid(),
		name: "Steins gate Plushie",
		price: 1200,
		category: "lifestyle",
		rating: 3.9,
		discount: 33,
		src: "https://m.media-amazon.com/images/I/61OnqTDsruS._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Transformers autobot T-shirt",
		price: 2500,
		category: "clothing",
		rating: 2.9,
		discount: 64,
		src: "https://d1x7zurbps6occ.cloudfront.net/product/large/1099537-325662.jpg",
	},
	{
		_id: uuid(),
		name: "The Three body problem book 1",
		price: 4500,
		category: "books",
		rating: 4.9,
		discount: 27,
		src: "https://m.media-amazon.com/images/I/919XM42JQlL._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "The Three body problem book 2",
		price: 2500,
		category: "books",
		rating: 2.5,
		discount: 17,
		src: "https://m.media-amazon.com/images/I/81015NXB2pL._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "The Three body problem book 3",
		price: 1500,
		category: "books",
		rating: 3.9,
		discount: 77,
		src: "https://m.media-amazon.com/images/I/91MfIt8mhaL._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "DUNE: The Graphic Novel, Book 1: Dune: Book 1 (Volume 1)",
		price: 5000,
		category: "books",
		rating: 3.5,
		discount: 23,
		src: "https://m.media-amazon.com/images/I/71SZk092xML._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Rick and Morty Wars Maxi Poster",
		price: 550,
		category: "wallart",
		rating: 4,
		discount: 55,
		src: "https://d1x7zurbps6occ.cloudfront.net/product/large/725123-192724.jpg",
	},
	{
		_id: uuid(),
		name: "The Mandalorian Coffee Mug",
		price: 1000,
		category: "lifestyle",
		rating: 1.6,
		discount: 35,
		src: "https://d1x7zurbps6occ.cloudfront.net/product/large/1071780-317673.jpg",
	},
	{
		_id: uuid(),
		name: "Vintage Coyboy bepop phone case - iphone 13",
		price: 2000,
		category: "accessories",
		rating: 3.6,
		discount: 15,
		src: "https://m.media-amazon.com/images/I/81ILf5dEM8L._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Tokyo Revengers Manjiro enamel pin",
		price: 2000,
		category: "accessories",
		rating: 1.6,
		discount: 35,
		src: "https://m.media-amazon.com/images/I/51AoBHBaPpL._AC_UL480_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Starwars The Mandolorian Note Book",
		price: 1500,
		category: "stationery",
		rating: 2.3,
		discount: 30,
		src: "https://d1x7zurbps6occ.cloudfront.net/product/large/1060032-316057.jpg",
	},

	{
		_id: uuid(),
		name: "Back to the future Men's Tshirt",
		price: 3500,
		category: "clothing",
		rating: 3,
		discount: 45,
		src: "https://d1x7zurbps6occ.cloudfront.net/product/large/1077870-319062.jpg",
	},

	{
		_id: uuid(),
		name: "A wrinkle in time book (paperback)",
		price: 2500,
		category: "books",
		rating: 3.2,
		discount: 9,
		src: "https://m.media-amazon.com/images/I/81yap8yKGwL._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Neon genesis evangelion  poster",
		price: 1500,
		category: "wallart",
		rating: 2.5,
		discount: 15,
		src: "https://m.media-amazon.com/images/I/61MXLfB3SiL._AC_UL480_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Ghost in the Shell Motoko Kusanagi Figurine",
		price: 850,
		category: "accessories",
		rating: 4.2,
		discount: 35,
		src: "https://m.media-amazon.com/images/I/61jPfTXDsaL._AC_UL480_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Flowers for algernon Book (paperback)",
		price: 550,
		category: "books",
		rating: 1.7,
		discount: 25,
		src: "https://m.media-amazon.com/images/I/3108OHxY7IL._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Steins gate hoodie",
		price: 4550,
		category: "clothing",
		rating: 4.7,
		discount: 60,
		src: "https://m.media-amazon.com/images/I/61vwUx+HMKL._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Starwars the Mandalorian Child bad",
		price: 2000,
		category: "lifestyle",
		rating: 4.6,
		discount: 15,
		src: "https://d1x7zurbps6occ.cloudfront.net/product/large/1106538-330116.jpg",
	},
	{
		_id: uuid(),
		name: "Serial Experiments Lain Glitch Cover NoteBook",
		price: 500,
		category: "stationery",
		rating: 3.6,
		discount: 85,
		src: "https://m.media-amazon.com/images/I/613-AD-2xnL._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Starwars Pencil case",
		price: 80,
		category: "stationery",
		rating: 4.7,
		discount: 5,
		src: "https://d1x7zurbps6occ.cloudfront.net/product/large/1060010-316060.jpg",
	},
	{
		_id: uuid(),
		name: "Steins gate Plushie",
		price: 1200,
		category: "lifestyle",
		rating: 3.9,
		discount: 33,
		src: "https://m.media-amazon.com/images/I/61OnqTDsruS._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "Transformers autobot T-shirt",
		price: 2500,
		category: "clothing",
		rating: 2.9,
		discount: 64,
		src: "https://d1x7zurbps6occ.cloudfront.net/product/large/1099537-325662.jpg",
	},
	{
		_id: uuid(),
		name: "The Three body problem book 1",
		price: 4500,
		category: "books",
		rating: 4.9,
		discount: 27,
		src: "https://m.media-amazon.com/images/I/919XM42JQlL._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "The Three body problem book 2",
		price: 2500,
		category: "books",
		rating: 2.5,
		discount: 17,
		src: "https://m.media-amazon.com/images/I/81015NXB2pL._AC_UY327_FMwebp_QL65_.jpg",
	},
	{
		_id: uuid(),
		name: "The Three body problem book 3",
		price: 1500,
		category: "books",
		rating: 3.9,
		discount: 77,
		src: "https://m.media-amazon.com/images/I/91MfIt8mhaL._AC_UY327_FMwebp_QL65_.jpg",
	},
];
