const actionTypes = {
	LOAD_DATA: "LOAD_DATA",
	LOW_TO_HIGH: "LOW_TO_HIGH",
	HIGH_TO_LOW: "HIGH_TO_LOW",
	PRICE: "PRICE",
	ACCESSORIES: "ACCESSORIES",
	BOOKS: "BOOKS",
	CLOTHING: "CLOTHING",
	LIFESTYLE: "LIFESTYLE",
	STATIONERY: "STATIONERY",
	WALLART: "WALLART",
	RATING: "RATING",
	DISCOUNT: "DISCOUNT",
	CLEAR: "CLEAR",
	ADD_TO_CART: "ADD_TO_CART",
	SET_CART: "SET_CART",
	INCREMENT: "INCREMENT",
	DECREMENT: "DECREMENT",
};

export { actionTypes };
