const actionTypes = {
	LOAD_DATA: "LOAD_DATA",

	SORT_TYPE: ["LOW_TO_HIGH", "HIGH_TO_LOW"],
	PRICE: "PRICE",
	CATEGORY: [
		"ACCESSORIES",
		"BOOKS",
		"CLOTHING",
		"LIFESTYLE",
		"STATIONERY",
		"WALLART",
	],
	RATING: "RATING",
	DISCOUNT: "DISCOUNT",
	CLEAR: "CLEAR",
};

export { actionTypes };
