const actionTypes = {
	LOAD_DATA: "LOAD_DATA",

	SORT_TYPE: ["LOW_TO_HIGH", "HIGH_TO_LOW"],
	PRICE: "PRICE",
	ACCESSORIES: "ACCESSORIES",
	BOOKS: "BOOKS",
	CLOTHING: "CLOTHING",
	LIFESTYLE: "LIFESTYLE",
	STATIONERY: "STATIONERY",
	WALLART: "WALLART",
	RATING: "RATING",
	DISCOUNT: "DISCOUNT",
	CLEAR: "CLEAR",
};

export { actionTypes };
